### ISSUE TITLE
/var/www/artisan: Permission denied

### ISSUE THREAD

**Issue by chrispappas** [atrauzzi/laravel-diy-paas-preview#1]
When starting up the container (using both `docker-compose up` and `sudo docker-compose up`) I get an error for the `laravel-worker` as follows:

```
laravel-worker   | /usr/local/bin/artisan: line 3: /var/www/artisan: Permission denied
laravel-webapp   | [03-Feb-2016 20:30:36] NOTICE: fpm is running, pid 1
laravel-webapp   | [03-Feb-2016 20:30:36] NOTICE: ready to handle connections
laravel-webapp   | [03-Feb-2016 20:30:36] NOTICE: systemd monitor interval set to 10000ms
laravel-worker exited with code 126
```

I think this is preventing it from running the composer install step, so I don't get anything hosted at localhost:8080, however I do see the access logs showing up in the console window.

This is running in an xubuntu 15.10 desktop VM on Windows 7 64 bit Virtualbox 5.0.14 host

**Comment by atrauzzi** [comment]
I'll patch this up right away, but try doing a `chmod +x` on `artisan` in your project dir.

**Comment by atrauzzi** [comment]
I've also improved the instructions a little to include a few normal laravel steps.

**Comment by chrispappas** [comment]
This works great now that I have updated (and properly read the instructions).

I have everything up and running and it all seems to be working nicely! Thanks for addressing this.
