### ISSUE TITLE
Build the dev image on docker hub

### ISSUE THREAD

**Issue by atrauzzi** [atrauzzi/laravel-diy-paas-preview#24]
'cause damn it takes forever

**Comment by dalekurt** [comment]
Would the dev image allow for debugging. I'm actually thinking about modify the existing to provide debugging information for my developer.

**Comment by atrauzzi** [comment]
You want to enable xdebug?

**Comment by atrauzzi** [comment]
Hey @dalekurt open another ticket if you want xdebug.  The dev container is building on docker hub now, so that's this ticket wrapped up :)
