### ISSUE TITLE
Cannot start worker service

### ISSUE THREAD

**Issue by cdomansky** [atrauzzi/laravel-diy-paas-preview#34]
After cloning the repo and spinning up the containers the worker container has an error and wlll not load. 

ERROR: for ccdc-worker  Cannot start service worker: oci runtime error: container_linux.go:265: starting container process caused "exec: \"artisan\": exCreating ccdc-cron ... done

ERROR: for worker  Cannot start service worker: oci runtime error: container_linux.go:265: starting container process caused "exec: \"artisan\": executable file not found in $PATH"

**Comment by atrauzzi** [comment]
cc. https://github.com/canadian-cyber-defence-challenge/ccdc-website/issues/12
